[package]
name = "no_std_printf_no_panic_handler"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = { version = "0.2", default-features = false }
panic-halt = "0.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
